name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.10.4

      - name: Set TF_LOG to DEBUG
        run: echo "TF_LOG=DEBUG" >> $GITHUB_ENV

      - name: Terraform Init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_client_id: ${{ secrets.ARM_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
          TF_VAR_service_principal_object_id: "53adf89f-7ab4-4582-afb8-df4a61022a8e"
          TF_VAR_address_space: '["10.0.0.0/16"]'
          TF_VAR_key_vault_name: "AzureFusionKeyVault"
          TF_VAR_key_vault_resource_group: "AzureFusionRG"
          TF_VAR_location: "EastUS"
          TF_VAR_resource_group_name: "AzureFusionRG"
          TF_VAR_vm_name: "fusionvm"
          TF_VAR_nic_name: "fusion-nic"
          TF_VAR_prefix: "fusion"
          TF_VAR_subnet_names: '{"webapp": "webapp-subnet", "bastion": "AzureBastionSubnet", "gateway": "gateway-subnet", "database": "database-subnet", "admin": "admin-subnet"}'
          TF_VAR_vnet_name: "fusion-vnet"
          TF_VAR_lb_name: "fusion-lb"
          TF_VAR_lb_frontend_ip_name: "fusion-lb-frontend"
          TF_VAR_lb_backend_pool_name: "fusion-lb-backend"
          TF_VAR_lb_rule_name: "fusion-lb-rule"
          TF_VAR_public_ip_names: '{"lb": "fusion-lb-pip"}'
          TF_VAR_bastion_host_name: "fusion-bastion"
          TF_VAR_vm_name_2: "fusionvm2"
          TF_VAR_nic_name_2: "fusion-nic-2"
          TF_VAR_onprem_subnet_names: '{"subnet1": "onprem-subnet1", "subnet2": "onprem-subnet2"}'
          TF_VAR_onprem_vnet_name: "onprem-vnet"
          TF_VAR_sql_server_name: "azfusionsql"
          TF_VAR_vm_size: "Standard_B1s"
          TF_VAR_main_vnet_id: "/subscriptions/970b1e0b-75cb-4721-99df-45bf7e5fb2c1/resourceGroups/AzureFusionRG/providers/Microsoft.Network/virtualNetworks/fusion-vnet"
          TF_VAR_onprem_vnet_id: "/subscriptions/970b1e0b-75cb-4721-99df-45bf7e5fb2c1/resourceGroups/AzureFusionRG/providers/Microsoft.Network/virtualNetworks/onprem-vnet"
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_client_id: ${{ secrets.ARM_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
          TF_VAR_service_principal_object_id: "53adf89f-7ab4-4582-afb8-df4a61022a8e"
          TF_VAR_address_space: '["10.0.0.0/16"]'
          TF_VAR_key_vault_name: "AzureFusionKeyVault"
          TF_VAR_key_vault_resource_group: "AzureFusionRG"
          TF_VAR_location: "EastUS"
          TF_VAR_resource_group_name: "AzureFusionRG"
          TF_VAR_vm_name: "fusionvm"
          TF_VAR_nic_name: "fusion-nic"
          TF_VAR_prefix: "fusion"
          TF_VAR_subnet_names: '{"webapp": "webapp-subnet", "bastion": "AzureBastionSubnet", "gateway": "gateway-subnet", "database": "database-subnet", "admin": "admin-subnet"}'
          TF_VAR_vnet_name: "fusion-vnet"
          TF_VAR_lb_name: "fusion-lb"
          TF_VAR_lb_frontend_ip_name: "fusion-lb-frontend"
          TF_VAR_lb_backend_pool_name: "fusion-lb-backend"
          TF_VAR_lb_rule_name: "fusion-lb-rule"
          TF_VAR_public_ip_names: '{"lb": "fusion-lb-pip"}'
          TF_VAR_bastion_host_name: "fusion-bastion"
          TF_VAR_vm_name_2: "fusionvm2"
          TF_VAR_nic_name_2: "fusion-nic-2"
          TF_VAR_onprem_subnet_names: '{"subnet1": "onprem-subnet1", "subnet2": "onprem-subnet2"}'
          TF_VAR_onprem_vnet_name: "onprem-vnet"
          TF_VAR_sql_server_name: "azfusionsql"
          TF_VAR_vm_size: "Standard_B1s"
          TF_VAR_main_vnet_id: "/subscriptions/970b1e0b-75cb-4721-99df-45bf7e5fb2c1/resourceGroups/AzureFusionRG/providers/Microsoft.Network/virtualNetworks/fusion-vnet"
          TF_VAR_onprem_vnet_id: "/subscriptions/970b1e0b-75cb-4721-99df-45bf7e5fb2c1/resourceGroups/AzureFusionRG/providers/Microsoft.Network/virtualNetworks/onprem-vnet"
        run: terraform apply -auto-approve